### ISSUE TITLE
NameError: name 'os' is not defined. Did you forget to import 'os'?

### ISSUE THREAD

**Issue by BigManTT** [Atropa-Solanaceae/proXXy#13]
WARNING: Please run pip install hrequests[all] for automated browsing support.
Traceback (most recent call last):
  File "C:\Users\bim\Downloads\Python\proXXy-main\proXXy-main\proXXy\proXXy.py", line 588, in <module>
    parameters()
  File "C:\Users\bim\Downloads\Python\proXXy-main\proXXy-main\proXXy\proXXy.py", line 183, in parameters
    banner()
  File "C:\Users\bim\Downloads\Python\proXXy-main\proXXy-main\proXXy\proXXy.py", line 126, in banner
    os.system("title proXXy -- by Solanaceae")
    ^^
NameError: name 'os' is not defined. Did you forget to import 'os'?

**Comment by Atropa-Solanaceae** [comment]
Will be fixed in the next release, coming soon.

**Comment by Atropa-Solanaceae** [comment]
Released!
