### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Kittyskj** [Atropa-Solanaceae/proXXy#18]
Python 3.10.6
Windows 11
Installed last update + last requirements

Traceback (most recent call last):
  File "C:\Users\tester\Desktop\proXXy-2.4\proXXy.py", line 221, in <module>
    main()
  File "C:\Users\tester\Desktop\proXXy-2.4\proXXy.py", line 206, in main
    proxies = utils.cproxy_sources()
AttributeError: module 'utils' has no attribute 'cproxy_sources'

**Comment by Atropa-Solanaceae** [comment]
Run the update script and try it again

**Comment by Kittyskj** [comment]
Fixed Thx
